version: '3.2'

services:
  com_pg:
    image: postgres:14.3
    container_name: com_pg
    restart: unless-stopped
    environment:
        POSTGRES_USER: com_user
        POSTGRES_PASSWORD: com_password
        POSTGRES_DB: com_pg
        TZ: "UTC"
        PGTZ: "UTC"
    ports:
      - 5432:5432
    networks:
      - default